### ISSUE TITLE
[BUG] Cannot change video quality

### ISSUE THREAD

**Issue by trieuduong1602** [bl5ck/md-player#1]
When I watch video in full screen mode, I click on "setting" but I cannot see panel for change video quality. Maybe this panel was overlayed by video

**Comment by bl5ck** [comment]
Thanks for helping us with improvement. I'm investigating. It sounds like `ScreenFull` skipped DOM node of the settings popup while focusing on the player,

**Comment by bl5ck** [comment]
Fixed.
